### ISSUE TITLE
可以增加对acss的支持嘛

### ISSUE THREAD

**Issue by yaguangZang** [mofada/AxmlPlugin#2]
axml在webstorm上终于可以正常编辑了，样式部分的acss文件还是无法支持

**Comment by mofada** [comment]
acss的文件可以让他使用css的样式去编辑

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/76399581-cd23da80-63b9-11ea-8e32-f396bc1b18be.png)

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/76399632-e75db880-63b9-11ea-801b-848a67e5902f.png)

acss和css很相似, 唯一的区别就是单位的问题, alt  + enter 可以关掉红色提示, 看起来就像这样子

**Comment by yaguangZang** [comment]
完美解决acss问题，3Q
